### ISSUE TITLE
Crates.io package has outdated dependencies.

### ISSUE THREAD

**Issue by WooterTheTroubleshooter** [daboross/screeps-in-rust-via-wasm#131]
The package on crates.io does not have the dependencies changed since version 0.2.1.

I would like to be able to update cargo-screeps, but I need the newer reqwest version because of a dependency on an obsolete version of rust-openssl.

https://github.com/seanmonstar/reqwest/issues/336

**Comment by daboross** [comment]
Thanks for mentioning this!

It's probably a good time to release new versions of the tools anyways since there aren't many WIP prs.

**Comment by daboross** [comment]
Should be fixed now by #132.
