### ISSUE TITLE
Unresolved import ConstructionSite.

### ISSUE THREAD

**Issue by WooterTheTroubleshooter** [daboross/screeps-in-rust-via-wasm#14]
I am trying to build the starter kit. Unfortunately I'm running into the following issue when trying to compile.

```
error[E0432]: unresolved import
 --> /home/wouter/.cargo/registry/src/github.com-1ecc6299db9ec823/screeps-game-api-0.0.10/src/objects/impls/construction_site.rs:3:6
  |
3 | use {ConstructionSite, ReturnCode, StructureType};
  |      ^^^^^^^^^^^^^^^^
error: aborting due to previous error
For more information about this error, try `rustc --explain E0432`.
error: Could not compile `screeps-game-api`.

```

**Comment by daboross** [comment]
Hm, there may be an error in the last published version. I'll see if I can reproduce this.

**Comment by daboross** [comment]
This seems to be a regression in rustc introduced recently. I don't get the error compiling on rust 1.28.0 stable, but I do on beta 1.29.0-beta.4.

**Comment by WooterTheTroubleshooter** [comment]
Ok I have managed a workaround by doing the following:
rustup toolchain install nightly-2018-07-19.

However now I am getting errors trying to compile the rust starter code. I'll post an issue in the starter repository.
