### ISSUE TITLE
Skip Memory via RawMemory.get and serde

### ISSUE THREAD

**Issue by ASalvail** [daboross/screeps-in-rust-via-wasm#16]
One of the expensive things in screeps is parsing the memory to a state where it's usable. Given that this already compiles to web assembly and that serde is already being used, how about we skip the `MemoryReference`s and directly parse the result of `RawMemory.get()`.

This would involve making sure to call `RawMemory.set()`, but I believe it's well worth the risk to gain in performance and parse the memory directly to a struct.

Any thoughts, reasons why this is a good/bad idea?

**Comment by daboross** [comment]
A few reasons why I've not made this the default:

- JSON parsing is indeed expensive, and JSON.parse is one of the fastest implementations available. Even if we can use a WASM implementation, it's not necessarily going to be faster than the native speed that's offered by default.
- Parsing memory ourselves harms interoperability with existing JavaScript codebases. It'd be confusing if the default behavior had updates not propagating to JavaScript until the end of the tick.
- If it were to be done automatically in `screeps-game-api`, it would require some global state within the WASM module, and more logic than I'd care to include in these API bindings.

With that said, I don't think it's a bad idea at all for a project using `screeps-game-api` to do this! We should definitely be exposing `RawMemory.get` and `RawMemory.set` from this crate if we aren't already, and those could be used in conjuction with `serde_json::from_slice` and `serde_json::to_vec` to implement local memory parsing on top of `screeps-game-api`.

**Comment by ASalvail** [comment]
All very good reasons. 
The one thing I'm looking at that would make it belong more in this package was the auto struct parsing. However, after tinkering with it for a bit, it seemed highly dependant on what you actually want to put in memory, circling back to the idea of doing a user-side parsing.

I added the two methods for `raw_memory`, I'll open a PR tonight.

**Comment by daboross** [comment]
Cool, thanks!

For auto-parsing, I think `serde_json` does have us covered. It wouldn't be a bad idea to publish things like this though- I can imagine a "common screeps-rust patterns" crate could work well built on top of `screeps-game-api` itself.
