### ISSUE TITLE
Why is RoomObjectProperties trait unsafe?

### ISSUE THREAD

**Issue by ASalvail** [daboross/screeps-in-rust-via-wasm#20]
This one has been puzzling me for the last few days.

This trait is marked unsafe, yet I cannot find why.
```rust
pub unsafe trait RoomObjectProperties:
    AsRef<Reference> + Into<Reference> + HasPosition
{
    fn try_from(obj: RoomObject) -> Option<Self>;

    fn room(&self) -> Room {
        js_unwrap!(@{self.as_ref()}.room)
    }
}
```

None of the supertrait are unsafe, try_from seems memory safe and I don't see anymore problems here with `js_unwrap!()` than anywhere else in the package. So, I'm stumped.

I removed all the `unsafe` from `objects/mod.rs` and the compiler didn't complain. Am I too naive to believe this somehow validates my point?

Assuming I'm wrong, can we document what are the safety assumptions that are made?

**Comment by ASalvail** [comment]
The other option might be to explicitely deal with `Result`s everywhere. Thing is, it would get heavy.

**Comment by daboross** [comment]
Yeah- I mean we could use `Result` for all these operations we expect to succeed, but it really would be bad style. If someone implements `RoomObjectProperties` for something it shouldn't be implemented for, I'd count that as a program logic error, and that's what panics are for.
