### ISSUE TITLE
js_unwrap_array! should assert that something is an array before unwrapping it

### ISSUE THREAD

**Issue by daboross** [daboross/screeps-in-rust-via-wasm#24]
Right now we trust the only code using it, but if something is ever unexpectedly an object rather than an array, who knows what could happen.

It's there so that we can correctly unwrap arrays that aren't `global.Array`, so it'll need some other way to verify that something is an array, but I'm sure we can think of that.

**Comment by ASalvail** [comment]
Fixed in #43

**Comment by daboross** [comment]
Thanks- missed this.
