### ISSUE TITLE
Needs implementation

### ISSUE THREAD

**Issue by ASalvail** [daboross/screeps-in-rust-via-wasm#30]
A todo list of yet unimplemented API

- [x] `Game.market.*` (Transactions and Orders need testing)
- [x] `Game.market.incomingTransactions`
- [x] `Game.market.outgoingTransactions`
- [x] `Game.market.orders`
- [x] `Game.market.get_all_orders`
- [x] `Game.market.get_order`
- [x] `Game.notify`
- [x] `Game.map.findExit` (implement callback)
- [x] `Game.map.findRoute` (has callback)
- [x] `Game.getObjectById` (for objects that have an id, but do not implement `RoomObjectProperties`)
- [x] `Creep.body` (part of it is in `creep.parts`)
- [x] `Creep.saying`
- [x] `Creep.drop`
- [x] `Creep.moveByPath`
- [x] `Creep.moveTo` (implement `opts`)
- [x] `Creep.notifyWhenAttacked`
- [x] `Flag.*`
- [x] `Mineral.*`
- [x] `Nuke.*`
- [x] `Ressouce.id`
- [x] `Room.memory`
- [ ] `Room.visual` See #46
- [x] `Room.serializePath`
- [x] `Room.deserializePath`
- [x] `Room.findExitTo`
- [x] `Room.findPath`
- [x] `Room.getPositionAt`
- [x] `Room.lookAt`
- [x] `Room.lookAtArea`
- [ ] `RoomPosition.findClosestByPath` see #55 
- [x] `RoomPosition.findPathTo`
- [x] `RoomPosition.isEqualxy`
- [x] `RoomPosition.look`
- [ ] `RoomVisual.*` See #46 
- [x] `StructureController.activateSafeMode`
- [x] `StructureController.unclaim`
- [x] `StructureExtension.*` (I don't believe we can go with `HasStore`)
- [x] `StructureExtractor.*`
- [x] `StructureKeeperLair.*`
- [x] `StructureLab.*`
- [x] `StructureLink.*`
- [x] `StructureNuker.*`
- [x] `StructureObserver.*`
- [x] `StructurePowerBank.*`
- [x] `StructurePowerSpawn.*`
- [x] `StructurePortal.*`
- [x] `StructureRampart.*`
- [x] `StructureRoad.*`
- [x] `StructureSpawn.memory`
- [x] `StructureSpawn.spawnCreep` (options part, see todo in code)
- [x] `StructureSpawn.recycleCreep`
- [x] `StructureSpawn.renewCreep`
- [x] `StructureTerminal.*`
- [x] `StructureTower.*`
- [x] `Tombstone.id`
- [ ] Update constants. There are a lot that are missing.

### Relevant notes
There seem to be a need for a few more traits such as:
- [x] `Decays` -> `tickToDecay`
- [x] `HasEnergyStore` -> for towers, spawns, extensions, rampart, [link, lab, terminal, creep, container, storage].
- [x] `HasHitPoints` -> `hits` and `hitsMax`

Prior to solving a lot of other problems, there is a need for:
- [x] A `Path` struct
- [x] A way to sanely get arrays back from js (fixed from using `TryFrom<Array>`)
- [x] A way to parse objects deeply (e.g. for market orders) (using serde)
- [x] A way to encode the return value of all `look` methods (from `Room` and `RoomPosition`)

**Comment by daboross** [comment]
How do you think it would be best to handle newly added things?

I can imagine them either being added here, or put in a separate "implement update xxx" issue.

Thinking about this since https://blog.screeps.com/2018/09/changelog-2018-09-22/ adds some new things we'll want to add support for.

**Comment by ASalvail** [comment]
So long as we don't declare v1.0, it doesn't really matter. Afterward, I'd add an issue per unit of code.
Ideally, it might be nice to track it in a github project.

For the ones you pointed out, I'd add them here once they reach public release there (we might think of doing beta/ptr version later once the important stuff is taken care of).

**Comment by daboross** [comment]
Alright, I'll make individual issues then; we might as well start now. I don't feel like 1.0 is a huge milestone, it's only really a commitment to stability.

 The things in that blog post have hit public release as of the post.

**Comment by ASalvail** [comment]
Oh... at least, other than the event log, most of those are fairly straightforward.

**Comment by ASalvail** [comment]
I did most of the work that I wanted to do before starting. The remaining points are reiterated in #46, #55 and #88.
