### ISSUE TITLE
`read_string` was renamed `read_to_string` in latest nightly Rust

### ISSUE THREAD

**Issue by cai-lw** [daboross/screeps-in-rust-via-wasm#5]
So it doesn't compile now.
https://github.com/daboross/screeps-in-rust-via-wasm/blob/744445a69f2e44023ee42724120da3ea70030761/cargo-screeps/src/main.rs#L1
Depending on nightly can easily break back compatibility. I think it would be better to avoid nightly whenever possible.

**Comment by daboross** [comment]
True!

When I was originally making this I didn't realize anyone else would use it, so I went for full unstability since I'm fine with that.

It is probably a good idea to shift away from that now that there's more usage, though.

**Comment by cai-lw** [comment]
@daboross I've decided to write my Screeps AI in Rust. I am not familiar with JS and its toolchain, so Rust is currently my best choice. Actually I've tried playing Screeps with JS for a while but I thought it would take me too long to get used to JS and dynamic language is prone to silly errors.

**Comment by daboross** [comment]
Cool!

I chose to start this with Rust for similar reasons.

If you find anything else not working in the repository, do feel free to open more issues and/or prs!
