### ISSUE TITLE
`Room.Terrain` wrapper and related methods

### ISSUE THREAD

**Issue by daboross** [daboross/screeps-in-rust-via-wasm#57]
In screeps as of https://blog.screeps.com/2018/09/changelog-2018-09-22/.

Required parts:
- https://docs.screeps.com/api/#Room-Terrain
- https://docs.screeps.com/api/#Room.getTerrain
- https://docs.screeps.com/api/#Game.map.getRoomTerrain
- Remove `game::map::get_terrain_at`

**Comment by ASalvail** [comment]
Implementing the terrain, I came upon [num-derive](https://crates.io/crates/num-derive) from [this blog post](https://www.enodev.fr/posts/rusticity-convert-an-integer-to-an-enum.html) as a replacement for `enum_primitive`.

Have you heard of it before? Any opinions?

**Comment by ASalvail** [comment]
Do you know of any way we could interface directly with the buffer that is already in WASM from https://docs.screeps.com/api/#Room.Terrain.getRawBuffer ?

**Comment by daboross** [comment]
re: `num-derive`: I had not heard of this- it looks like a good alternative. I don't think there's any good reason we're using `enum_primitive` instead of it.

----

With the raw buffer: I think we can use the same method as `LocalCostMatrix::as_uploaded`, just keeping the `UnsafeTypedArray<u8>` local to the method and not exposed.

We'd first create either a 2500-element `Vec<u8>`, or `[u8; 2500]`. Vec probably makes more sense.

We'd then wrap it into an `UnsafeTypedArray<u8>` and pass it to the method. If it completes successfully, it should copy the bytes into our `Vec` directly and we can just return that from the method.

It might also be worth it to make a `LocalRoomTerrain` structure wrapping a 2500-length `Vec<u8>` which could be created like other local structures.

I can work on this, or it could be part of this PR if you want.

For reference: https://github.com/daboross/screeps-in-rust-via-wasm/blob/82bec2de6da5a361c68734354048b814f9b8ac6d/screeps-game-api/src/pathfinder.rs#L71-L89
