### ISSUE TITLE
We could be using unsigned types in more places

### ISSUE THREAD

**Issue by daboross** [daboross/screeps-in-rust-via-wasm#74]
Right now we have a number of APIs which should be limited to positive values returning `i32`. Unless there are reasons to keep this, I think using `u32` anywhere we can reasonably assume a value is unsigned would be better.

I think there was a reason we had things as `i32`, but I really can't remember what it is. If whatever it was comes up we might not want to do this?

**Comment by daboross** [comment]
I think the reason I'd chosen to use `i32` was because of the pitfalls of subtracting unsigned integers and running into underflow easily.

At this time I'm thinking it's more important to show that we guarantee/expect things to be unsigned than it is to provide an ease-of-use feature making things signed. This could be discussed, though!

**Comment by ASalvail** [comment]
@daboross was this all addressed in #83 ?

**Comment by daboross** [comment]
I think so. We still have `i32` for `Find` values, but that's probably fine.
