### ISSUE TITLE
Get enum from memory reference

### ISSUE THREAD

**Issue by L3nn0x** [daboross/screeps-in-rust-via-wasm#95]
Hello,

I'd like to set and get an enum from the memory, but it seems like there are no getter for it. I found the MemoryReference::set<T: JsSerialize>() but there is no MemoryReference::get<T: JsDeserialize>(). Any idea how I could do that?

Thanks!

**Comment by ASalvail** [comment]
The getters are per type. If you expect to get a `f64`, you should use `MemoryReference::path_f64(path)`.

This is made to insure the values extracted from the memory are typed. If you don't want to type them, it should be always possible to extract them via `MemoryReference::path_string(path)` or `your_reference.string(key)`.

**Comment by Stargateur** [comment]
I do it in my fork, https://github.com/Stargateur/screeps-in-rust-via-wasm/commit/7daa17ee1095fabb9ba4fb355b6fa6366fe3c3b5. However, if you want stock an enum I think you must use https://docs.rs/stdweb/0.4.8/stdweb/macro.js_deserializable.html and https://docs.rs/stdweb/0.4.8/stdweb/macro.js_serializable.html to make it work with custom type.

**Comment by L3nn0x** [comment]
That's what I wanted to do, use js_serializable and js_deserialisable. What I find weird is that the setter is implemented for T, but there is no getter for T. (Btw, the setter works for enums that implement JSSerialize, so I'd expect it to work for JSDeserialize as well).

I can make a PR for get and get_path, otherwise I'll just implement it in my fork.

**Comment by daboross** [comment]
I think a generic `get` was originally avoided because it could be used incorrectly with RoomObject types like `Creep`, but #45 and the change to return `Option<Result<>>` rather than `Option` have largely fixed those concerns for me.

I'd be good with adding `get` and `get_path`. If @ASalvail agrees, feel free to PR or one of us could implement it as well.

**Comment by WooterTheTroubleshooter** [comment]
So, I am trying to use the set<T> and get<T> methods to store and retrieve a screeps::RoomPosition to memory, but I'm not entirely sure how to correctly use this.

```
match creep.memory().get<screeps::RoomPosition>("target")
{
    Ok(target) => move_to(target),
    Err(_) => warn!("Something went wrong trying to get target from creep")
}
```
Is this the correct way to go use this method?
